version: "3"
services:
    my_story_app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: my_story_app
        restart: always
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html/
        networks:
            - my-story-network
        volumes:
            - ./:/var/www/html/
        depends_on:
            - my_story_db
    my_story_webserver:
        image: nginx:alpine
        container_name: my_story_webserver
        restart: always
        tty: true
        networks:
            - my-story-network
            - traefik

        volumes:
            - ./:/var/www/html/
            - ./docker/nginx:/etc/nginx/conf.d/

        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.my_story_app.rule=Host(`${APP_HOST:-pelatihan.semanja.localhost}`)"
            - "traefik.http.routers.my_story_app.tls=true"
            - "traefik.http.routers.my_story_app.entrypoints=websecure"
            - "traefik.http.routers.my_story_app.tls.certresolver=myresolver"
            - "traefik.http.services.my_story_app.loadbalancer.server.port=80"
            - "traefik.docker.network=traefik"
    my_story_db:
        image: mariadb:10
        container_name: my_story_db
        restart: always
        tty: true
        environment:
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        networks:
            - my-story-network
        volumes:
            - dbdata:/var/lib/mysql

networks:
    my-story-network:
        driver: bridge
    traefik:
        external: true
volumes:
    dbdata:
        driver: local
